[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM3
monitor_port = COM3

lib_deps =
    miguelbalboa/MFRC522 @ ^1.4.10
    bblanchon/ArduinoJson @ ^6.21.3
